### ISSUE TITLE
It shows 1 room though you enter 0 guests

### ISSUE THREAD

**Issue by banidprajapati** [banidprajapati/HostelStays-HostelManagementSystem#11]

**Comment by KritikaTldr** [comment]
before solving this issue
![image](https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/128012810/7b92438a-b6cb-46bd-b5db-25da7495e7e7)


after solving this issue
![image](https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/128012810/fe7dd63b-3e5c-4cf9-acd7-dcf79a0db1ba)
