### ISSUE TITLE
Date bug

### ISSUE THREAD

**Issue by banidprajapati** [banidprajapati/HostelStays-HostelManagementSystem#12]
When you first enter the checkout date, the check in date can be any date. 
<img width="480" alt="image" src="https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/74712385/c4e7b76e-7f8b-451e-8b2a-18f50515e275">

**Comment by Aayush-33** [comment]
agadi minus ma yekhaye pani confirm booking garda chai error message aauxa ani price ni NAN hunxa

![image](https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/119646537/e4509148-e49d-47a1-a94d-1ecb5dadff75)
