### ISSUE TITLE
Bookings 0 huda ni no of guest 1

### ISSUE THREAD

**Issue by xela-ale** [banidprajapati/HostelStays-HostelManagementSystem#14]
<img width="566" alt="image" src="https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/115362789/ddb1e291-0ce1-4654-9fdc-595251907ab8">
<img width="519" alt="image" src="https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/115362789/f6545ca8-72e3-4d34-b20e-cd7085cba4f8">

**Comment by Aayush-33** [comment]
0 guests 0 rooms 

![image](https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/119646537/4c86eca8-65c0-4d04-aeed-f810783fdde2)
