### ISSUE TITLE
Footer is not working.

### ISSUE THREAD

**Issue by banidprajapati** [banidprajapati/HostelStays-HostelManagementSystem#16]
<img width="915" alt="image" src="https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/74712385/53985b4f-fc00-4dd9-abe9-9333bad71356">

the link does not work. Privacy policy matrai chaleko cha. aru kei chaleko chaina. 4 days from 2 May to 6 May samma ko time ma footer complete garna parne thiyo. bhako chaina.

**Comment by KritikaTldr** [comment]
Footer is now working.

![image](https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/128012810/de54e46c-26a5-436a-9241-d5418b03eeb3)
![image](https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/128012810/33a7395b-df7c-46ae-8b09-5dd58a14325d)
![image](https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/128012810/6ded780e-8bbc-478c-bc5d-d990590bb9c4)

When I click on the number, it gets copied and saved to the clipboard.
![image](https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/128012810/b870bcf4-e59c-41d2-92fc-2b19843251a7)


When I click on Gmail or Facebook, it opens the corresponding link.
