### ISSUE TITLE
Show password while logging in not working.

### ISSUE THREAD

**Issue by banidprajapati** [banidprajapati/HostelStays-HostelManagementSystem#17]
show password icon now showing. 
<img width="315" alt="image" src="https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/74712385/cc7b902f-051a-4642-aaf5-d5bca5750499">
<img width="329" alt="image" src="https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/74712385/9659eacb-b207-44ae-8a7a-3e3d3bfaf4c9">
<img width="328" alt="image" src="https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/74712385/fb177725-42fd-4b0d-b48a-dfbf14fa957b">
<img width="329" alt="image" src="https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/74712385/a62d78b9-7572-43ae-9030-1ccbacbd0b01">

**Comment by KritikaTldr** [comment]
The "Show Password" feature is now working properly and the issue has been resolved.

![image](https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/128012810/a93d22d8-63b9-4837-9cc2-c0942e98b6bb)



![image](https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/128012810/23fbf095-1723-4286-b1d7-d23bdf974988)


![image](https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/128012810/9b651de9-f9b5-4bd4-ad16-3ccfbfd3ca3f)
