### ISSUE TITLE
Book your stay frontend not working properly

### ISSUE THREAD

**Issue by banidprajapati** [banidprajapati/HostelStays-HostelManagementSystem#19]
<img width="412" alt="image" src="https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/74712385/d88a7667-6708-495f-872a-c7fe32265a03">

**Comment by KritikaTldr** [comment]
![image](https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/128012810/34eae55c-b662-4608-87f3-816602029864)


Issue with the input date has been solved.
