### ISSUE TITLE
Redirect bhako chaina if city chaina bhaney. 

### ISSUE THREAD

**Issue by banidprajapati** [banidprajapati/HostelStays-HostelManagementSystem#20]
DO error handling here. 0 hostels are located in the entered city.
<img width="950" alt="image" src="https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/74712385/dfde407e-17b5-48ff-ac62-9453073fdeb4">

**Comment by KritikaTldr** [comment]
When there are no hostels found for the provided city name, display the error message "No hostels found in that city."

![image](https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/128012810/53ce366c-e953-49ea-9614-79909f747332)
