### ISSUE TITLE
Date error aayerxa fix garda price aafi auto updated hudaina maunally matra halda price update hunxa

### ISSUE THREAD

**Issue by xela-ale** [banidprajapati/HostelStays-HostelManagementSystem#22]
<img width="1031" alt="image" src="https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/115362789/d94b9ad9-7534-4541-a04e-409c2299e5db">

<img width="1118" alt="image" src="https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/115362789/1b56ac3b-9def-493b-bf75-42e01b260dce">

<img width="1068" alt="image" src="https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/115362789/0d5aa85e-3ea8-4703-bedd-199ee53ff631">

**Comment by KritikaTldr** [comment]
The error has been fixed and the code is now running smoothly without any issues.
![image](https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/128012810/053fba2a-03e7-4418-9c85-f15d11174935)


![image](https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/128012810/1cfc4e66-706c-4069-8c0a-5e33ab0a4078)


![image](https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/128012810/89ac8bd3-f5a2-4fab-af4f-9472be6eb595)
