### ISSUE TITLE
Past Data stored xa  clear hudaina 

### ISSUE THREAD

**Issue by xela-ale** [banidprajapati/HostelStays-HostelManagementSystem#23]
![image](https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/115362789/41be5c2a-c730-45e1-a002-32fe5ec718e7)

**Comment by KritikaTldr** [comment]
Before deleteing a hostel

![image](https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/128012810/64b4490d-8fc0-4eae-8957-b4475c03f351)





After deleting a hostel
![image](https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/128012810/3a0c028a-5123-4f45-bf7f-9a47198f9570)

![image](https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/128012810/939b8ce1-a73e-446e-9f2d-293d140086f5)
