### ISSUE TITLE
Sign up

### ISSUE THREAD

**Issue by xela-ale** [banidprajapati/HostelStays-HostelManagementSystem#3]
![274f5f77-9f5a-4a13-af19-399e7e8a73ad](https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/115362789/c3a7baae-ccd5-42ea-9062-03c05739def1)
It Signups without anything being written.

**Comment by KritikaTldr** [comment]
![image](https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/128012810/a30f6253-32e9-476c-b7bb-ecbaa141cf45)
