### ISSUE TITLE
Same email address can result to errors with unclear instructions

### ISSUE THREAD

**Issue by banidprajapati** [banidprajapati/HostelStays-HostelManagementSystem#4]
When the user tries to create an account with the email address that already exists. A proper error is not shown.
<img width="301" alt="image" src="https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/74712385/85f182cf-a06a-4dec-ba65-3f01e6ab8073">

**Comment by KritikaTldr** [comment]
![image](https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/128012810/a021e270-4855-4d78-815a-59d4a065d268)
