### ISSUE TITLE
Guest zero huda ni confirm hunxa booking and billing page ma redirect hunxa

### ISSUE THREAD

**Issue by xela-ale** [banidprajapati/HostelStays-HostelManagementSystem#6]
<img width="572" alt="image" src="https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/115362789/b57572f7-be51-4cb5-b78f-7e8e7038285e">

**Comment by Aayush-33** [comment]
0 guests huda redirect hunna error message dekhauxa

![image](https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/119646537/d1b3f3a0-4584-4f8d-81d6-8c220fc1c376)
