### ISSUE TITLE
Details empty huda ni billing  ma aayo

### ISSUE THREAD

**Issue by xela-ale** [banidprajapati/HostelStays-HostelManagementSystem#7]
<img width="528" alt="image" src="https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/115362789/994cf43a-e1fe-417d-bc2f-4c42038b240a">

**Comment by Aayush-33** [comment]
date haru default xa and if guest text field empty bhayo vane 0 hunxa automatically 
![image](https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/119646537/f8eed13a-c9f9-408d-b499-74302a8eea82)
