### ISSUE TITLE
Landing Page ma hostel list should be in reversed order making the latest one at top

### ISSUE THREAD

**Issue by banidprajapati** [banidprajapati/HostelStays-HostelManagementSystem#9]

**Comment by KritikaTldr** [comment]
before solving issue
![image](https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/128012810/e9ac0a54-d3b1-468f-b90e-0696febda571)




after solving issue
![image](https://github.com/banidprajapati/HostelStays-HostelManagementSystem/assets/128012810/5d90874c-7a72-4989-ac2e-5fd3670cabcb)
